apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-carts
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: carts
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: carts
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-catalogue
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: catalogue
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: catalogue
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-front-end
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: web
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: front-end
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-orders
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: orders
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: orders
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-payment
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: payment
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: payment
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-shipping
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: shipping
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: shipping
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-shop-user
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: user
    scheme: http
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: user
