apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cargotracker
  name: cargotracker
  namespace: cargotracker-monolith
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: cargotracker-monolith
  tags:
  - items:
    tag: latest
