apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add
  namespace: <PROJECT>
  labels:
    app: add
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
      - name: add
        image: <CONTAINER>
