apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subtract
  namespace: <PROJECT>
  labels:
    app: subtract
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subtract
    spec:
      containers:
      - name: subtract
        image: <CONTAINER>
